OPENAI_API_KEY = "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"
QDRANT_URL = 'https://6a38e28f-ce64-4260-a1e3-c274775bb9ee.eu-west-2-0.aws.cloud.qdrant.io'
QDRANT_API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwiZXhwIjoxNzQ3NDE3NjMxfQ.n_vHSB6DltGHSozZBBculkzq-X2xHWq0gglc03P2tBw'
